version: '3.8'

services:
  camping-water:
    build: .
    container_name: camping-water-container
    environment:
      - ENV=production
    volumes:
      - ./output:/app/output
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: camping-water-management-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


